# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Radiance_config = debug
  RadianceEditor_config = debug

else ifeq ($(config),release)
  Radiance_config = release
  RadianceEditor_config = release

else ifeq ($(config),dist)
  Radiance_config = dist
  RadianceEditor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Radiance RadianceEditor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Radiance:
ifneq (,$(Radiance_config))
	@echo "==== Building Radiance ($(Radiance_config)) ===="
	@${MAKE} --no-print-directory -C Radiance -f Makefile config=$(Radiance_config)
endif

RadianceEditor: Radiance
ifneq (,$(RadianceEditor_config))
	@echo "==== Building RadianceEditor ($(RadianceEditor_config)) ===="
	@${MAKE} --no-print-directory -C RadianceEditor -f Makefile config=$(RadianceEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Radiance -f Makefile clean
	@${MAKE} --no-print-directory -C RadianceEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Radiance"
	@echo "   RadianceEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"